name: Deploying TrackableObject
run-name: ${{ github.actor }} merge branch with master
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "warmup"
