name: Releasing New Version Of TrackableObject
run-name: ${{ github.actor }} New Release
on:
  release:
    types: [created]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - run: npm i
      - run: npm run build
      - run: npm run test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
